shallow_clone: true

os:
  - Visual Studio 2017

configuration:
  - Debug
  - RelWithDebInfo

install:
  - cmake -G "Visual Studio 15 2017 Win64" -DRUSH_RENDER_API=VK -B.\Build\vs2017-vk -H.

build:
  project: .\Build\vs2017-vk\Rush.sln
