language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env:
        - CMAKE_ARGS="-DRUSH_RENDER_API=MTL"
    - os: linux
      compiler: gcc
      env:
        - CMAKE_ARGS="-DRUSH_RENDER_API=VK"
    # - os: windows
    #   env:
    #     - CMAKE_ARGS="-A x64 -DRUSH_RENDER_API=VK"

notifications:
  email: false

script:
  - mkdir build
  - cd build
  - cmake ${CMAKE_ARGS} ..
  - make
