language: cpp

matrix:
  include:
    - compiler: clang
      os: osx

notifications:
  email: false

osx_image: xcode9.4

script:
  - mkdir build
  - cd build
  - cmake -DRUSH_RENDER_API=MTL ..
  - make
